input_lvs = [
    {
        'X': (0, 10.01, 0.01),
        'name': 'Productivity on the project',
        'terms': {
            'always slacking off': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1), 'centroid': 0.965},
            'not productive': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 0.48, 2.71), 'centroid': 2.568},
            'less productive than average': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 0.42, 3.71), 'centroid': 3.251},
            'productivity is average': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 0.27, 5.35), 'centroid': 5.240},
            'more productive than average': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 0.40, 6.81), 'centroid': 6.276},
            'productive': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 0.47, 7.91), 'centroid': 7.122},
            'very productive': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1), 'centroid': 8.679}
        }
    },
    {
        'X': (0, 10.01, 0.01),
        'name': 'Teamwork & Leadership',
        'terms': {
            'antisocial and rude': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1), 'centroid': 0.965},
            'shy': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 0.48, 2.71), 'centroid': 2.568},
            'unpleasant to work with': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 0.42, 3.71), 'centroid': 3.251},
            'average team member': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 0.27, 5.35), 'centroid': 5.240},
            'pleasant to work with': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 0.40, 6.81), 'centroid': 6.276},
            'outgoing': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 0.47, 7.91), 'centroid': 7.122},
            'leader in a group': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1), 'centroid': 8.679}
        }
    },
    {
        'X': (0, 10.01, 0.01),
        'name': 'Hard Skills & Knowledge',
        'terms': {
            'can\'t perform tasks on the project': {'umf': ('trapmf', 0, 0, 0.59, 3.95), 'lmf': ('trapmf', 0, 0, 0.09, 1.32, 1), 'centroid': 0.965},
            'severely lacking knowledge and hard skills': {'umf': ('trapmf', 0.28, 2.00, 3.00, 5.22), 'lmf': ('trapmf', 1.79, 2.37, 2.37, 0.48, 2.71), 'centroid': 2.568},
            'lacking knowledge and hard skills': {'umf': ('trapmf', 0.98, 2.75, 4.00, 5.41), 'lmf': ('trapmf', 2.79, 3.30, 3.30, 0.42, 3.71), 'centroid': 3.251},
            'about average': {'umf': ('trapmf', 2.38, 4.50, 6.00, 8.18), 'lmf': ('trapmf', 4.79, 5.12, 5.12, 0.27, 5.35), 'centroid': 5.240},
            'more knowledge than needed for current tasks': {'umf': ('trapmf', 4.02, 5.65, 7.00, 8.41), 'lmf': ('trapmf', 5.89, 6.34, 6.34, 0.40, 6.81), 'centroid': 6.276},
            'good hard skills and knowledge': {'umf': ('trapmf', 4.38, 6.50, 7.75, 9.62), 'lmf': ('trapmf', 6.79, 7.25, 7.25, 0.47, 7.91), 'centroid': 7.122},
            'outstanding skills and abilities': {'umf': ('trapmf', 5.21, 8.27, 10, 10), 'lmf': ('trapmf', 7.66, 9.82, 10, 10, 1), 'centroid': 8.679}
        }
    }
]


output_lv = {
    'X': (0, 10.1, 0.1),
    'name': 'Decision regarding employee',
    'terms': {
        'lay off': {'umf': ('trapmf', 0, 0, 1.13, 1.47), 'lmf': ('trapmf', 0, 0, 0.65, 0.99, 1)},
        'demote': {'umf': ('trapmf', 1.19, 1.55, 3.19, 3.68), 'lmf': ('trapmf', 2.2, 2.37, 2.37, 2.61, 1)},
        'keep': {'umf': ('trapmf', 3.34, 3.89, 6.98, 7.31), 'lmf': ('trapmf', 5, 5.42, 5.42, 5.73, 1)},
        'give a bonus': {'umf': ('trapmf', 7.1, 7.31, 7.67, 8.02), 'lmf': ('trapmf', 7.29, 7.49, 7.49, 7.77, 1)},
        'promote': {'umf': ('trapmf', 7.89, 8.25, 8.93, 9.23), 'lmf': ('trapmf', 8.44, 8.6, 8.6, 8.76, 1)},
        'promote with a bonus': {'umf': ('trapmf', 8.95, 9.17, 10, 10), 'lmf': ('trapmf', 9.43, 9.81, 10, 10, 1)}
        }
}


rule_base = [
    (("always slacking off", "antisocial and rude", "can't perform tasks on the project"), "lay off"),
    (("always slacking off", "antisocial and rude", "severely lacking knowledge and hard skills"), "lay off"),
    (("always slacking off", "antisocial and rude", "lacking knowledge and hard skills"), "lay off"),
    (("always slacking off", "antisocial and rude", "about average"), "lay off"),
    (("always slacking off", "antisocial and rude", "more knowledge than needed for current tasks"), "lay off"),
    (("always slacking off", "antisocial and rude", "good hard skills and knowledge"), "lay off"),
    (("always slacking off", "antisocial and rude", "outstanding skills and abilities"), "lay off"),
    (("always slacking off", "shy", "can't perform tasks on the project"), "lay off"),
    (("always slacking off", "shy", "severely lacking knowledge and hard skills"), "lay off"),
    (("always slacking off", "shy", "lacking knowledge and hard skills"), "lay off"),
    (("always slacking off", "shy", "about average"), "demote"),
    (("always slacking off", "shy", "more knowledge than needed for current tasks"), "demote"),
    (("always slacking off", "shy", "good hard skills and knowledge"), "demote"),
    (("always slacking off", "shy", "outstanding skills and abilities"), "demote"),
    (("always slacking off", "unpleasant to work with", "can't perform tasks on the project"), "lay off"),
    (("always slacking off", "unpleasant to work with", "severely lacking knowledge and hard skills"), "lay off"),
    (("always slacking off", "unpleasant to work with", "lacking knowledge and hard skills"), "lay off"),
    (("always slacking off", "unpleasant to work with", "about average"), "demote"),
    (("always slacking off", "unpleasant to work with", "more knowledge than needed for current tasks"), "demote"),
    (("always slacking off", "unpleasant to work with", "good hard skills and knowledge"), "demote"),
    (("always slacking off", "unpleasant to work with", "outstanding skills and abilities"), "keep"),
    (("always slacking off", "average team member", "can't perform tasks on the project"), "lay off"),
    (("always slacking off", "average team member", "severely lacking knowledge and hard skills"), "demote"),
    (("always slacking off", "average team member", "lacking knowledge and hard skills"), "demote"),
    (("always slacking off", "average team member", "about average"), "demote"),
    (("always slacking off", "average team member", "more knowledge than needed for current tasks"), "demote"),
    (("always slacking off", "average team member", "good hard skills and knowledge"), "keep"),
    (("always slacking off", "average team member", "outstanding skills and abilities"), "keep"),
    (("always slacking off", "pleasant to work with", "can't perform tasks on the project"), "lay off"),
    (("always slacking off", "pleasant to work with", "severely lacking knowledge and hard skills"), "demote"),
    (("always slacking off", "pleasant to work with", "lacking knowledge and hard skills"), "demote"),
    (("always slacking off", "pleasant to work with", "about average"), "demote"),
    (("always slacking off", "pleasant to work with", "more knowledge than needed for current tasks"), "keep"),
    (("always slacking off", "pleasant to work with", "good hard skills and knowledge"), "keep"),
    (("always slacking off", "pleasant to work with", "outstanding skills and abilities"), "keep"),
    (("always slacking off", "outgoing", "can't perform tasks on the project"), "lay off"),
    (("always slacking off", "outgoing", "severely lacking knowledge and hard skills"), "demote"),
    (("always slacking off", "outgoing", "lacking knowledge and hard skills"), "demote"),
    (("always slacking off", "outgoing", "about average"), "keep"),
    (("always slacking off", "outgoing", "more knowledge than needed for current tasks"), "keep"),
    (("always slacking off", "outgoing", "good hard skills and knowledge"), "keep"),
    (("always slacking off", "outgoing", "outstanding skills and abilities"), "keep"),
    (("always slacking off", "leader in a group", "can't perform tasks on the project"), "lay off"),
    (("always slacking off", "leader in a group", "severely lacking knowledge and hard skills"), "demote"),
    (("always slacking off", "leader in a group", "lacking knowledge and hard skills"), "keep"),
    (("always slacking off", "leader in a group", "about average"), "keep"),
    (("always slacking off", "leader in a group", "more knowledge than needed for current tasks"), "keep"),
    (("always slacking off", "leader in a group", "good hard skills and knowledge"), "keep"),
    (("always slacking off", "leader in a group", "outstanding skills and abilities"), "keep"),
    (("not productive", "antisocial and rude", "can't perform tasks on the project"), "lay off"),
    (("not productive", "antisocial and rude", "severely lacking knowledge and hard skills"), "lay off"),
    (("not productive", "antisocial and rude", "lacking knowledge and hard skills"), "lay off"),
    (("not productive", "antisocial and rude", "about average"), "demote"),
    (("not productive", "antisocial and rude", "more knowledge than needed for current tasks"), "demote"),
    (("not productive", "antisocial and rude", "good hard skills and knowledge"), "demote"),
    (("not productive", "antisocial and rude", "outstanding skills and abilities"), "demote"),
    (("not productive", "shy", "can't perform tasks on the project"), "lay off"),
    (("not productive", "shy", "severely lacking knowledge and hard skills"), "lay off"),
    (("not productive", "shy", "lacking knowledge and hard skills"), "lay off"),
    (("not productive", "shy", "about average"), "demote"),
    (("not productive", "shy", "more knowledge than needed for current tasks"), "demote"),
    (("not productive", "shy", "good hard skills and knowledge"), "demote"),
    (("not productive", "shy", "outstanding skills and abilities"), "keep"),
    (("not productive", "unpleasant to work with", "can't perform tasks on the project"), "lay off"),
    (("not productive", "unpleasant to work with", "severely lacking knowledge and hard skills"), "lay off"),
    (("not productive", "unpleasant to work with", "lacking knowledge and hard skills"), "lay off"),
    (("not productive", "unpleasant to work with", "about average"), "demote"),
    (("not productive", "unpleasant to work with", "more knowledge than needed for current tasks"), "demote"),
    (("not productive", "unpleasant to work with", "good hard skills and knowledge"), "keep"),
    (("not productive", "unpleasant to work with", "outstanding skills and abilities"), "keep"),
    (("not productive", "average team member", "can't perform tasks on the project"), "demote"),
    (("not productive", "average team member", "severely lacking knowledge and hard skills"), "demote"),
    (("not productive", "average team member", "lacking knowledge and hard skills"), "demote"),
    (("not productive", "average team member", "about average"), "demote"),
    (("not productive", "average team member", "more knowledge than needed for current tasks"), "keep"),
    (("not productive", "average team member", "good hard skills and knowledge"), "keep"),
    (("not productive", "average team member", "outstanding skills and abilities"), "keep"),
    (("not productive", "pleasant to work with", "can't perform tasks on the project"), "demote"),
    (("not productive", "pleasant to work with", "severely lacking knowledge and hard skills"), "demote"),
    (("not productive", "pleasant to work with", "lacking knowledge and hard skills"), "demote"),
    (("not productive", "pleasant to work with", "about average"), "keep"),
    (("not productive", "pleasant to work with", "more knowledge than needed for current tasks"), "keep"),
    (("not productive", "pleasant to work with", "good hard skills and knowledge"), "keep"),
    (("not productive", "pleasant to work with", "outstanding skills and abilities"), "keep"),
    (("not productive", "outgoing", "can't perform tasks on the project"), "demote"),
    (("not productive", "outgoing", "severely lacking knowledge and hard skills"), "demote"),
    (("not productive", "outgoing", "lacking knowledge and hard skills"), "keep"),
    (("not productive", "outgoing", "about average"), "keep"),
    (("not productive", "outgoing", "more knowledge than needed for current tasks"), "keep"),
    (("not productive", "outgoing", "good hard skills and knowledge"), "keep"),
    (("not productive", "outgoing", "outstanding skills and abilities"), "keep"),
    (("not productive", "leader in a group", "can't perform tasks on the project"), "demote"),
    (("not productive", "leader in a group", "severely lacking knowledge and hard skills"), "keep"),
    (("not productive", "leader in a group", "lacking knowledge and hard skills"), "keep"),
    (("not productive", "leader in a group", "about average"), "keep"),
    (("not productive", "leader in a group", "more knowledge than needed for current tasks"), "keep"),
    (("not productive", "leader in a group", "good hard skills and knowledge"), "keep"),
    (("not productive", "leader in a group", "outstanding skills and abilities"), "promote"),
    (("less productive than average", "antisocial and rude", "can't perform tasks on the project"), "lay off"),
    (("less productive than average", "antisocial and rude", "severely lacking knowledge and hard skills"), "lay off"),
    (("less productive than average", "antisocial and rude", "lacking knowledge and hard skills"), "lay off"),
    (("less productive than average", "antisocial and rude", "about average"), "demote"),
    (("less productive than average", "antisocial and rude", "more knowledge than needed for current tasks"), "demote"),
    (("less productive than average", "antisocial and rude", "good hard skills and knowledge"), "demote"),
    (("less productive than average", "antisocial and rude", "outstanding skills and abilities"), "keep"),
    (("less productive than average", "shy", "can't perform tasks on the project"), "lay off"),
    (("less productive than average", "shy", "severely lacking knowledge and hard skills"), "lay off"),
    (("less productive than average", "shy", "lacking knowledge and hard skills"), "lay off"),
    (("less productive than average", "shy", "about average"), "demote"),
    (("less productive than average", "shy", "more knowledge than needed for current tasks"), "demote"),
    (("less productive than average", "shy", "good hard skills and knowledge"), "keep"),
    (("less productive than average", "shy", "outstanding skills and abilities"), "keep"),
    (("less productive than average", "unpleasant to work with", "can't perform tasks on the project"), "lay off"),
    (("less productive than average", "unpleasant to work with", "severely lacking knowledge and hard skills"), "lay off"),
    (("less productive than average", "unpleasant to work with", "lacking knowledge and hard skills"), "lay off"),
    (("less productive than average", "unpleasant to work with", "about average"), "demote"),
    (("less productive than average", "unpleasant to work with", "more knowledge than needed for current tasks"), "keep"),
    (("less productive than average", "unpleasant to work with", "good hard skills and knowledge"), "give a bonus"),
    (("less productive than average", "unpleasant to work with", "outstanding skills and abilities"), "give a bonus"),
    (("less productive than average", "average team member", "can't perform tasks on the project"), "demote"),
    (("less productive than average", "average team member", "severely lacking knowledge and hard skills"), "demote"),
    (("less productive than average", "average team member", "lacking knowledge and hard skills"), "demote"),
    (("less productive than average", "average team member", "about average"), "keep"),
    (("less productive than average", "average team member", "more knowledge than needed for current tasks"), "keep"),
    (("less productive than average", "average team member", "good hard skills and knowledge"), "keep"),
    (("less productive than average", "average team member", "outstanding skills and abilities"), "keep"),
    (("less productive than average", "pleasant to work with", "can't perform tasks on the project"), "demote"),
    (("less productive than average", "pleasant to work with", "severely lacking knowledge and hard skills"), "demote"),
    (("less productive than average", "pleasant to work with", "lacking knowledge and hard skills"), "keep"),
    (("less productive than average", "pleasant to work with", "about average"), "keep"),
    (("less productive than average", "pleasant to work with", "more knowledge than needed for current tasks"), "keep"),
    (("less productive than average", "pleasant to work with", "good hard skills and knowledge"), "keep"),
    (("less productive than average", "pleasant to work with", "outstanding skills and abilities"), "keep"),
    (("less productive than average", "outgoing", "can't perform tasks on the project"), "demote"),
    (("less productive than average", "outgoing", "severely lacking knowledge and hard skills"), "keep"),
    (("less productive than average", "outgoing", "lacking knowledge and hard skills"), "give a bonus"),
    (("less productive than average", "outgoing", "about average"), "keep"),
    (("less productive than average", "outgoing", "more knowledge than needed for current tasks"), "keep"),
    (("less productive than average", "outgoing", "good hard skills and knowledge"), "give a bonus"),
    (("less productive than average", "outgoing", "outstanding skills and abilities"), "promote"),
    (("less productive than average", "leader in a group", "can't perform tasks on the project"), "keep"),
    (("less productive than average", "leader in a group", "severely lacking knowledge and hard skills"), "keep"),
    (("less productive than average", "leader in a group", "lacking knowledge and hard skills"), "give a bonus"),
    (("less productive than average", "leader in a group", "about average"), "keep"),
    (("less productive than average", "leader in a group", "more knowledge than needed for current tasks"), "keep"),
    (("less productive than average", "leader in a group", "good hard skills and knowledge"), "promote"),
    (("less productive than average", "leader in a group", "outstanding skills and abilities"), "promote"),
    (("productivity is average", "antisocial and rude", "can't perform tasks on the project"), "lay off"),
    (("productivity is average", "antisocial and rude", "severely lacking knowledge and hard skills"), "demote"),
    (("productivity is average", "antisocial and rude", "lacking knowledge and hard skills"), "demote"),
    (("productivity is average", "antisocial and rude", "about average"), "demote"),
    (("productivity is average", "antisocial and rude", "more knowledge than needed for current tasks"), "demote"),
    (("productivity is average", "antisocial and rude", "good hard skills and knowledge"), "keep"),
    (("productivity is average", "antisocial and rude", "outstanding skills and abilities"), "keep"),
    (("productivity is average", "shy", "can't perform tasks on the project"), "demote"),
    (("productivity is average", "shy", "severely lacking knowledge and hard skills"), "demote"),
    (("productivity is average", "shy", "lacking knowledge and hard skills"), "demote"),
    (("productivity is average", "shy", "about average"), "demote"),
    (("productivity is average", "shy", "more knowledge than needed for current tasks"), "keep"),
    (("productivity is average", "shy", "good hard skills and knowledge"), "keep"),
    (("productivity is average", "shy", "outstanding skills and abilities"), "keep"),
    (("productivity is average", "unpleasant to work with", "can't perform tasks on the project"), "demote"),
    (("productivity is average", "unpleasant to work with", "severely lacking knowledge and hard skills"), "demote"),
    (("productivity is average", "unpleasant to work with", "lacking knowledge and hard skills"), "demote"),
    (("productivity is average", "unpleasant to work with", "about average"), "keep"),
    (("productivity is average", "unpleasant to work with", "more knowledge than needed for current tasks"), "keep"),
    (("productivity is average", "unpleasant to work with", "good hard skills and knowledge"), "keep"),
    (("productivity is average", "unpleasant to work with", "outstanding skills and abilities"), "keep"),
    (("productivity is average", "average team member", "can't perform tasks on the project"), "demote"),
    (("productivity is average", "average team member", "severely lacking knowledge and hard skills"), "demote"),
    (("productivity is average", "average team member", "lacking knowledge and hard skills"), "keep"),
    (("productivity is average", "average team member", "about average"), "give a bonus"),
    (("productivity is average", "average team member", "more knowledge than needed for current tasks"), "give a bonus"),
    (("productivity is average", "average team member", "good hard skills and knowledge"), "give a bonus"),
    (("productivity is average", "average team member", "outstanding skills and abilities"), "give a bonus"),
    (("productivity is average", "pleasant to work with", "can't perform tasks on the project"), "demote"),
    (("productivity is average", "pleasant to work with", "severely lacking knowledge and hard skills"), "keep"),
    (("productivity is average", "pleasant to work with", "lacking knowledge and hard skills"), "keep"),
    (("productivity is average", "pleasant to work with", "about average"), "give a bonus"),
    (("productivity is average", "pleasant to work with", "more knowledge than needed for current tasks"), "give a bonus"),
    (("productivity is average", "pleasant to work with", "good hard skills and knowledge"), "give a bonus"),
    (("productivity is average", "pleasant to work with", "outstanding skills and abilities"), "promote"),
    (("productivity is average", "outgoing", "can't perform tasks on the project"), "keep"),
    (("productivity is average", "outgoing", "severely lacking knowledge and hard skills"), "keep"),
    (("productivity is average", "outgoing", "lacking knowledge and hard skills"), "keep"),
    (("productivity is average", "outgoing", "about average"), "give a bonus"),
    (("productivity is average", "outgoing", "more knowledge than needed for current tasks"), "give a bonus"),
    (("productivity is average", "outgoing", "good hard skills and knowledge"), "promote"),
    (("productivity is average", "outgoing", "outstanding skills and abilities"), "promote"),
    (("productivity is average", "leader in a group", "can't perform tasks on the project"), "keep"),
    (("productivity is average", "leader in a group", "severely lacking knowledge and hard skills"), "keep"),
    (("productivity is average", "leader in a group", "lacking knowledge and hard skills"), "keep"),
    (("productivity is average", "leader in a group", "about average"), "give a bonus"),
    (("productivity is average", "leader in a group", "more knowledge than needed for current tasks"), "promote"),
    (("productivity is average", "leader in a group", "good hard skills and knowledge"), "promote"),
    (("productivity is average", "leader in a group", "outstanding skills and abilities"), "promote"),
    (("more productive than average", "antisocial and rude", "can't perform tasks on the project"), "lay off"),
    (("more productive than average", "antisocial and rude", "severely lacking knowledge and hard skills"), "demote"),
    (("more productive than average", "antisocial and rude", "lacking knowledge and hard skills"), "demote"),
    (("more productive than average", "antisocial and rude", "about average"), "demote"),
    (("more productive than average", "antisocial and rude", "more knowledge than needed for current tasks"), "keep"),
    (("more productive than average", "antisocial and rude", "good hard skills and knowledge"), "keep"),
    (("more productive than average", "antisocial and rude", "outstanding skills and abilities"), "keep"),
    (("more productive than average", "shy", "can't perform tasks on the project"), "demote"),
    (("more productive than average", "shy", "severely lacking knowledge and hard skills"), "demote"),
    (("more productive than average", "shy", "lacking knowledge and hard skills"), "demote"),
    (("more productive than average", "shy", "about average"), "keep"),
    (("more productive than average", "shy", "more knowledge than needed for current tasks"), "keep"),
    (("more productive than average", "shy", "good hard skills and knowledge"), "keep"),
    (("more productive than average", "shy", "outstanding skills and abilities"), "keep"),
    (("more productive than average", "unpleasant to work with", "can't perform tasks on the project"), "demote"),
    (("more productive than average", "unpleasant to work with", "severely lacking knowledge and hard skills"), "demote"),
    (("more productive than average", "unpleasant to work with", "lacking knowledge and hard skills"), "keep"),
    (("more productive than average", "unpleasant to work with", "about average"), "keep"),
    (("more productive than average", "unpleasant to work with", "more knowledge than needed for current tasks"), "keep"),
    (("more productive than average", "unpleasant to work with", "good hard skills and knowledge"), "keep"),
    (("more productive than average", "unpleasant to work with", "outstanding skills and abilities"), "keep"),
    (("more productive than average", "average team member", "can't perform tasks on the project"), "demote"),
    (("more productive than average", "average team member", "severely lacking knowledge and hard skills"), "keep"),
    (("more productive than average", "average team member", "lacking knowledge and hard skills"), "keep"),
    (("more productive than average", "average team member", "about average"), "give a bonus"),
    (("more productive than average", "average team member", "more knowledge than needed for current tasks"), "give a bonus"),
    (("more productive than average", "average team member", "good hard skills and knowledge"), "give a bonus"),
    (("more productive than average", "average team member", "outstanding skills and abilities"), "promote"),
    (("more productive than average", "pleasant to work with", "can't perform tasks on the project"), "keep"),
    (("more productive than average", "pleasant to work with", "severely lacking knowledge and hard skills"), "keep"),
    (("more productive than average", "pleasant to work with", "lacking knowledge and hard skills"), "keep"),
    (("more productive than average", "pleasant to work with", "about average"), "give a bonus"),
    (("more productive than average", "pleasant to work with", "more knowledge than needed for current tasks"), "give a bonus"),
    (("more productive than average", "pleasant to work with", "good hard skills and knowledge"), "promote"),
    (("more productive than average", "pleasant to work with", "outstanding skills and abilities"), "promote"),
    (("more productive than average", "outgoing", "can't perform tasks on the project"), "keep"),
    (("more productive than average", "outgoing", "severely lacking knowledge and hard skills"), "keep"),
    (("more productive than average", "outgoing", "lacking knowledge and hard skills"), "keep"),
    (("more productive than average", "outgoing", "about average"), "give a bonus"),
    (("more productive than average", "outgoing", "more knowledge than needed for current tasks"), "promote"),
    (("more productive than average", "outgoing", "good hard skills and knowledge"), "promote"),
    (("more productive than average", "outgoing", "outstanding skills and abilities"), "promote"),
    (("more productive than average", "leader in a group", "can't perform tasks on the project"), "keep"),
    (("more productive than average", "leader in a group", "severely lacking knowledge and hard skills"), "keep"),
    (("more productive than average", "leader in a group", "lacking knowledge and hard skills"), "keep"),
    (("more productive than average", "leader in a group", "about average"), "promote"),
    (("more productive than average", "leader in a group", "more knowledge than needed for current tasks"), "promote"),
    (("more productive than average", "leader in a group", "good hard skills and knowledge"), "promote"),
    (("more productive than average", "leader in a group", "outstanding skills and abilities"), "promote with a bonus"),
    (("productive", "antisocial and rude", "can't perform tasks on the project"), "lay off"),
    (("productive", "antisocial and rude", "severely lacking knowledge and hard skills"), "demote"),
    (("productive", "antisocial and rude", "lacking knowledge and hard skills"), "demote"),
    (("productive", "antisocial and rude", "about average"), "keep"),
    (("productive", "antisocial and rude", "more knowledge than needed for current tasks"), "keep"),
    (("productive", "antisocial and rude", "good hard skills and knowledge"), "keep"),
    (("productive", "antisocial and rude", "outstanding skills and abilities"), "keep"),
    (("productive", "shy", "can't perform tasks on the project"), "demote"),
    (("productive", "shy", "severely lacking knowledge and hard skills"), "demote"),
    (("productive", "shy", "lacking knowledge and hard skills"), "keep"),
    (("productive", "shy", "about average"), "keep"),
    (("productive", "shy", "more knowledge than needed for current tasks"), "keep"),
    (("productive", "shy", "good hard skills and knowledge"), "keep"),
    (("productive", "shy", "outstanding skills and abilities"), "keep"),
    (("productive", "unpleasant to work with", "can't perform tasks on the project"), "demote"),
    (("productive", "unpleasant to work with", "severely lacking knowledge and hard skills"), "keep"),
    (("productive", "unpleasant to work with", "lacking knowledge and hard skills"), "give a bonus"),
    (("productive", "unpleasant to work with", "about average"), "keep"),
    (("productive", "unpleasant to work with", "more knowledge than needed for current tasks"), "keep"),
    (("productive", "unpleasant to work with", "good hard skills and knowledge"), "give a bonus"),
    (("productive", "unpleasant to work with", "outstanding skills and abilities"), "promote"),
    (("productive", "average team member", "can't perform tasks on the project"), "keep"),
    (("productive", "average team member", "severely lacking knowledge and hard skills"), "keep"),
    (("productive", "average team member", "lacking knowledge and hard skills"), "keep"),
    (("productive", "average team member", "about average"), "give a bonus"),
    (("productive", "average team member", "more knowledge than needed for current tasks"), "give a bonus"),
    (("productive", "average team member", "good hard skills and knowledge"), "promote"),
    (("productive", "average team member", "outstanding skills and abilities"), "promote"),
    (("productive", "pleasant to work with", "can't perform tasks on the project"), "keep"),
    (("productive", "pleasant to work with", "severely lacking knowledge and hard skills"), "keep"),
    (("productive", "pleasant to work with", "lacking knowledge and hard skills"), "keep"),
    (("productive", "pleasant to work with", "about average"), "give a bonus"),
    (("productive", "pleasant to work with", "more knowledge than needed for current tasks"), "promote"),
    (("productive", "pleasant to work with", "good hard skills and knowledge"), "promote"),
    (("productive", "pleasant to work with", "outstanding skills and abilities"), "promote"),
    (("productive", "outgoing", "can't perform tasks on the project"), "keep"),
    (("productive", "outgoing", "severely lacking knowledge and hard skills"), "keep"),
    (("productive", "outgoing", "lacking knowledge and hard skills"), "give a bonus"),
    (("productive", "outgoing", "about average"), "promote"),
    (("productive", "outgoing", "more knowledge than needed for current tasks"), "promote"),
    (("productive", "outgoing", "good hard skills and knowledge"), "promote"),
    (("productive", "outgoing", "outstanding skills and abilities"), "promote with a bonus"),
    (("productive", "leader in a group", "can't perform tasks on the project"), "keep"),
    (("productive", "leader in a group", "severely lacking knowledge and hard skills"), "keep"),
    (("productive", "leader in a group", "lacking knowledge and hard skills"), "promote"),
    (("productive", "leader in a group", "about average"), "promote"),
    (("productive", "leader in a group", "more knowledge than needed for current tasks"), "promote"),
    (("productive", "leader in a group", "good hard skills and knowledge"), "promote with a bonus"),
    (("productive", "leader in a group", "outstanding skills and abilities"), "promote with a bonus"),
    (("very productive", "antisocial and rude", "can't perform tasks on the project"), "lay off"),
    (("very productive", "antisocial and rude", "severely lacking knowledge and hard skills"), "demote"),
    (("very productive", "antisocial and rude", "lacking knowledge and hard skills"), "keep"),
    (("very productive", "antisocial and rude", "about average"), "keep"),
    (("very productive", "antisocial and rude", "more knowledge than needed for current tasks"), "keep"),
    (("very productive", "antisocial and rude", "good hard skills and knowledge"), "keep"),
    (("very productive", "antisocial and rude", "outstanding skills and abilities"), "keep"),
    (("very productive", "shy", "can't perform tasks on the project"), "demote"),
    (("very productive", "shy", "severely lacking knowledge and hard skills"), "keep"),
    (("very productive", "shy", "lacking knowledge and hard skills"), "keep"),
    (("very productive", "shy", "about average"), "keep"),
    (("very productive", "shy", "more knowledge than needed for current tasks"), "keep"),
    (("very productive", "shy", "good hard skills and knowledge"), "keep"),
    (("very productive", "shy", "outstanding skills and abilities"), "promote"),
    (("very productive", "unpleasant to work with", "can't perform tasks on the project"), "keep"),
    (("very productive", "unpleasant to work with", "severely lacking knowledge and hard skills"), "keep"),
    (("very productive", "unpleasant to work with", "lacking knowledge and hard skills"), "give a bonus"),
    (("very productive", "unpleasant to work with", "about average"), "keep"),
    (("very productive", "unpleasant to work with", "more knowledge than needed for current tasks"), "keep"),
    (("very productive", "unpleasant to work with", "good hard skills and knowledge"), "promote"),
    (("very productive", "unpleasant to work with", "outstanding skills and abilities"), "promote"),
    (("very productive", "average team member", "can't perform tasks on the project"), "keep"),
    (("very productive", "average team member", "severely lacking knowledge and hard skills"), "keep"),
    (("very productive", "average team member", "lacking knowledge and hard skills"), "keep"),
    (("very productive", "average team member", "about average"), "give a bonus"),
    (("very productive", "average team member", "more knowledge than needed for current tasks"), "promote"),
    (("very productive", "average team member", "good hard skills and knowledge"), "promote"),
    (("very productive", "average team member", "outstanding skills and abilities"), "promote"),
    (("very productive", "pleasant to work with", "can't perform tasks on the project"), "keep"),
    (("very productive", "pleasant to work with", "severely lacking knowledge and hard skills"), "keep"),
    (("very productive", "pleasant to work with", "lacking knowledge and hard skills"), "keep"),
    (("very productive", "pleasant to work with", "about average"), "promote"),
    (("very productive", "pleasant to work with", "more knowledge than needed for current tasks"), "promote"),
    (("very productive", "pleasant to work with", "good hard skills and knowledge"), "promote"),
    (("very productive", "pleasant to work with", "outstanding skills and abilities"), "promote with a bonus"),
    (("very productive", "outgoing", "can't perform tasks on the project"), "keep"),
    (("very productive", "outgoing", "severely lacking knowledge and hard skills"), "keep"),
    (("very productive", "outgoing", "lacking knowledge and hard skills"), "promote"),
    (("very productive", "outgoing", "about average"), "promote"),
    (("very productive", "outgoing", "more knowledge than needed for current tasks"), "promote"),
    (("very productive", "outgoing", "good hard skills and knowledge"), "promote with a bonus"),
    (("very productive", "outgoing", "outstanding skills and abilities"), "promote with a bonus"),
    (("very productive", "leader in a group", "can't perform tasks on the project"), "keep"),
    (("very productive", "leader in a group", "severely lacking knowledge and hard skills"), "promote"),
    (("very productive", "leader in a group", "lacking knowledge and hard skills"), "promote"),
    (("very productive", "leader in a group", "about average"), "promote"),
    (("very productive", "leader in a group", "more knowledge than needed for current tasks"), "promote with a bonus"),
    (("very productive", "leader in a group", "good hard skills and knowledge"), "promote with a bonus"),
    (("very productive", "leader in a group", "outstanding skills and abilities"), "promote with a bonus")
]
